services:
  order-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: order-backend
    restart: always
    depends_on:
      order-db:
        condition: service_healthy
      kafka:
        condition: service_started
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5432/orderhandler
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${ORDERHANDLER_DB_PASSWORD}
    ports:
      - "8081:8081"
    networks:
      - handler

  audit-worker:
    build:
      context: ./workers/audit-java/
      dockerfile: Dockerfile
    container_name: audit-worker
    restart: always
    depends_on:
      order-db:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5432/analytics
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${ANALYTICS_DB_PASSWORD}
    networks:
      - handler

  inventory-worker:
    build:
      context: ./workers/inventory-go/
      dockerfile: Dockerfile
    container_name: inventory-worker
    restart: always
    depends_on:
      order-db:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      DATABASE_USER: ${DB_USER}
      DATABASE_PASS: ${INVENTORY_DB_PASSWORD}
      DATABASE_HOST: order-db
      DATABASE_PORT: 5432
      DATABASE_NAME: inventory
    networks:
      - handler

  payment-worker:
    build:
      context: ./workers/payment-java
      dockerfile: Dockerfile
    container_name: payment-worker
    restart: always
    depends_on:
      order-db:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5432/payments
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${PAYMENT_DB_PASSWORD}
      PAYMENT_ACCESS_TOKEN: ${PAYMENT_ACCESS_TOKEN}
    networks:
      - handler

  order-db:
    image: postgres:17-alpine
    container_name: order-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./infrastructure/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - handler
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d orderhandler"]
      interval: 3s
      timeout: 3s
      retries: 3

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

      # Mapeamento de Listeners (Comunicação Externa e Interna)
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'

      # Configurações para ambiente de desenvolvimento single-node
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - handler

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTARS_0_NAME: 'local'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka:29092'
    depends_on:
      - kafka
    networks:
      - handler

volumes:
  postgres_data:

networks:
  handler:
